package enums;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by XTREMSOFT on 11/15/2016.
 */
public enum eMessageCode {

    //Auhentication
    //LOGIN_AUTH_REQUEST(5),
    CLIENT_LOGIN_WITH2FACTOR (7),
    LOGIN_AUTH_RESPONSE(3),
    OTP_REQUEST(302),
    FCM_REQUEST(14),
    GUESTLOGIN_RCKEY_REQUEST(4),
    STATELIST_REQUEST(777),
    OPENACCOUNT_REQUEST(77),
    FORGOT_PASSWORD_VERIFY(12),
    GET_SERVER_SECONDIP (8),
    GET_SERVER_SECONDIP_BCAST(15),
    //BroadCast
    HEART_BEAT(6),
    CLIENT_BC_REGISTRATION(175),
    SHORT_MARKETWATCH(380),
    MARKETWATCH(5001),
    NEW_MARKETWATCH(7001),
    OLD_MULTIPLE_MARKETWATCH(8001),
    NEW_MULTIPLE_MARKETWATCH(9001),
        MARKETDEPTH(5002),
    NEW_MARKETDEPTH(7002),
    REMOVE_MARKETWATCH(92),
    REMOVE_MULTIPLE_MARKETWATCH(8092),
    REMOVE_MARKETDEPTH(5014),
    //for JBCast Start
    OpenInt(5003),
    TRADE_EXECUTION(5105),

    STATIC_MW(5071),
    LITE_MW(5095),
    LITE_MD(5097),
    INDICE_CODE_LITE_PRIME(1382),
    //for JBCast End
    TOP_TRADED(5011),
    REMOVE_TOPTRADED(6011),
    TOP_GAINER(5012),
    REMOVE_TOPGAINER(6012),
    TOP_LOOSER(5013),
    REMOVE_TOPLOOSER(6013),
    NEW_GROUPLIST(16),
    NEW_GROUPDETAILS(13),
    ADDSCRIPT_TOGROUP(602),
    DELETESCRIPT_FROMGROUP(603),
    SEARCHSCRIPT(701),
    SEARCHSCRIPT_NAME(725),
    SCRIPT_DETAILS_Request(706),
    SCRIPT_DETAILS_Response(702),
    NSEBSE_SCRIPTCODE(704),
    MULTI_SCRIPTDETAILS(705),
    ADDSCRIPT_INALERT(611),
    GETSCRIPRATE_FROMALERT(612),
    DELETESCRIPT_FROMALERT(613),

    NEW_CHART_TICKDATA(2802),
    INSERT_MOBILEINFO(1991),
    ERROR_LOG(1990),
    ANDROID_LOG(1989),
    HOMSG(85),
    TRADECONF(189),
    ORDERCONF(190),
    ORDERCONF_NEW(1190),
    LOGOFFRESP(61),
    DARTEVENT(5027),
    _INDICES(382),
    ADST(5010),

    //RC
    RC_RECONNECT(62),
    LOGIN_RC(1),
    RESEARCH_FETCH_SSO_LOGIN(43),
    MPIN_REQ(600),
    LOGIN_RC_FAILURE(257),
    LOGOFF_REQ(2),
    EXIT(3),

    CHGPWD(38),

    ORDER_BOOK_REQ(72),
    ORDER_BOOk_RESP(46),
    TRADE_BOOK_REQ(71),
    TRADE_BOOK_RESP(48),
    CFD_BOOK_RESP(47),
    MARGIN(40),
    MARGIN_NEW(201),
    MARGIN_RC(44),
    BRACKET_ORDER_REPORT(645),
    BRACKET_POSITION_REPORT(646),
    BRACKET_ORDERDETAIL_REPORT(647),
    HOLDING_RESPONSE(50),
    HOLDING_REQ(92),
    //HOLDING_REQ(90),
    SLBM_HOLDING_REPORT(241),

    MARGINTRADE_REQ(74),
    EXCHCANCELORDER_CASHINTRADEL_BCCHARTDATA(29),         //Intraday/Delivery
    INTRADAY_CHART(2029),
    EOD_CHART(2803),

    PLACE_ORDER_CASH(10),
    PLACE_ORDER_FNO(101),
    PLACE_ORDER_CURR(211),
    MODIFY_ORDER_CASH(110),
    MODIFY_ORDER_CURR(221),
    CANCEL_ORDER_CASH(120),
    CANCEL_ORDER_FNO(121),
    CANCEL_ORDER_CURR(231),
    POSITION_CONVERSION(26),

    EXCHPLACEORDER_CASH_FORGOTPWD(11),
    EXCHMODIFYORDER_CASH(21),
    EXCHCANCELORDER_CASH(31),

    EXCHPLACEORDER_DERIV_MODIFY_ORDER_FNO(111),
    EXCHMODIFYORDER_DERIV(121),
    EXCHCANCELORDER_DERIV(131),

    EXCHPLACEORDER_CURR(212),
    EXCHMODIFYORDER_CURR(222),
    EXCHCANCELORDER_CURR(232),

    EXCHPLACEORDER_SLBS(235),
    EXCHMODIFYORDER_SLBS(236),
    EXCHCANCELORDER_SLBS(237),

    cMSGCD_EXCHPLACEORDER_SLBS(238),
    cMSGCD_EXCHMODIFYORDER_SLBS(239),
    cMSGCD_EXCHCANCELORDER_SLBS(240),
    cMSGCD_EXCHKILLORDER_SLBS(243),

    EXCHTRADEORDER_CASHDERIV(150),

    SLTRIGGERED_CASH(51),
    SLTRIGGERED_DERIV(151),

    EXCHKILLORDER_BSE(32),
    EXCHKILLORDER_NSE(33),
    EXCHKILLORDER_DERIV(133),

    EXCHPLACEORDER_CASHINTRADEL(27),          //Intraday/Delivery
    EXCHMODIFYORDER_CASHINTRADEL(28),         //Intraday/Delivery


    //for after hours...
    BROKERMODIFYORDER_CASH_BCDELETEGROUP(20),
    BROKERCANCELORDER_CASH(30),

    BROKERPLACEORDER_CASHINTRADEL(17),        //Intraday/Delivery
    BROKERMODIFYORDER_CASHINTRADEL(18),       //Intraday/Delivery
    BROKERCANCELORDER_CASHINTRADEL_BCADDGROUP(19),       //Intraday/Delivery

    BROKERCANCELORDER_DERIV(130),

    GETNOTIFICATION_SETTING(712),
    SETNOTIFICATION_SETTING(711),

    START_STOP(1111),
    BC_MSG(199),
    ERROR_MSG(1999),
    MAINTENANCE_MSG(1997),
    NEWS_FETCH(22),
    NEWS_DISCLAIMER(24),
    NOTIFICATION_FETCH(25),

    SIMPLYSAVEHOME(2002),
    INVEST(2004),
    WITHDRAW(2003),
    BANKDETAIL(2005),
    PASSBOOK(2006),
    PARK_EARNREQUEST(2009),
    PASSBOOK_REF(2008),

    NEWS_SCRIP(3009),

    NOTIFICATION(10001),
    REFRESHDEPTH(10008),
    MKT_READ(10009),
    CURR_SYMBOL(801),
    SUMMARY_PASSBOOK(10011),

    ANALYTICS_OPTION_CHAIN(1032),
    ANALYTICS_GET_EXPIRY(1033),
    ANALYTICS_OPTION_CHAIN_NEW(1034),
    SCRIP_NAMES(1031),
    //RC NEW
    OCOPLACEREQ(400),
    OCOMODIFYREQ(410),
    OCOEXITREQ(420),
    CUSTOM_DIALOG(7781),
    LEDGER_DATA(1035),

    BONDORIPOAPPLY(1100)

    ;

    public int value;
    private eMessageCode(int value) {
        this.value = value;
    }
    private static final Map<Integer, eMessageCode> map = new HashMap<Integer, eMessageCode>();
    static {
        for (eMessageCode type : eMessageCode.values()) {
            map.put(type.value, type);
        }
    }
    public static eMessageCode valueOf(int value) {
        return map.get(value);
    }
}