package enums;

public enum eMessageCodeWealth {

    //NEW MF MYWEALTH
    MYWEALTH_SUMMARY(8),
    MYWEALTH_SESSIONERROR(11),
    //SHORT_LONG_TERM(234),
    //SHORT_LONG_TERM_NEW(235),
    SHORT_LONG_TERM_NEW(241),

    CHECK_HOLDING_UPDATE(239),

    HOLDING_REPOPRT(309),
    RUNNING_SIP(310),
    CAPITAL_GAIN_LOSS(395),
    DIVIDENT_SUMMARY(312),
    ASSET_ALLOCATION(313),
    DASHBOARD(314),
    GET_SCHEME_DETAILS(391),
    GET_SCHEME_SEARCH_DATA(392),
    GET_CLIENT_HOLDING_DATA(317),
    DOITYOURSELF_DATA(318),
    VENTURA_TOP_PICKS(319),
    SAVE_INVESTMENT_DATA(394),
    BUCKET_INVESTMENT_DATA(321),
    ASSETTYPE_DATA(322),
    FAMILY_DATA(323),
    MASTER_DATA(324),
    BANKDETAIL_DATA(325),
    SAVESIPMANDATE_DATA(326),
    REGISTER_SIP(327),
    ORDER_BOOK(328),
    GETSIPMANDATELIST_DATA(329),
    CLIENT_SESSION(330),
    NEGATIVE_BALANCE_ORDER(331),
    AVLBALANCE(1001),

    IPO_ISSUE_DETAILS(355),
    IPO_ISSUED_SAVE(351),
    IPO_UPI_DETAILS(352),
    IPO_UPI_VERIFY(361),
    IPO_UPI_SAVE(353),
    IPO_UPI_DELETE(354),
    IPO_GET_IPO_HANDLER_LIST(360),

    //SGB
    EG_ISSUE_DETAILS(356),
    EG_DP_ACCOUNT_DDETAILS(357),
    EG_ORDER_BOOK(358),
    EG_PLACE_ORDER(359),

    //FactSheet
    FACT_SHEET_SNAPSHOT(332),
    FACT_SHEET_PERFORMANCE(333),
    FACT_SHEET_PORTFOLIO(334),
    FACT_SHEET_FUND_MANAGER_DETAILS(335),
    FACT_SHEET_LUMPSUM_SIP_RETURNS(336),
    //NPS
    NPS_REPORT(337),
    //NFO
    NFO_REPORT(370),
    MISSED_SIP(375),
    BOND_ISSUEDETAILS(376),
    BOND_FORMDETAILS(377),
    BOND_SUBMITAPPLICATION(378),
    BOND_CLIENTDETAILS(379),
    BONDUPI_DETAILS(380),
    BONDVERIFYUPI_DETAILS(381),
    BONDSAVEUPI_DETAILS(382),
    BONDDELETEUPI_DETAILS(383),
    //VIDEO
    VIDEO_LINKS(386),
    CHECK_PAYMENTSTATUS(387),
    GET_CLIENT_BANKDETAILS(398),
    GET_CLIENT_MANDATE_COUNT(399),
    CHECK_EXISTING_SIP_MANDATE(400),
    GET_ONETIME_MANDATES(401),
    GET_NEXT_WORKING_DAY(402),
    GET_CHECK_MANDATE_STATUS(403),
    SAVE_SIPMANDATE_DATA_NEW(404),
    GET_CLIENT_BANK_DETAILS(405),
    GENERATE_RTAAUTHENTICATION_OTP(407),
    VALIDATE_RTA_AUTH_OTP(408),
    RESEND_RTA_AUTH_OTP(409)

    ;

    public int value;
    private eMessageCodeWealth(int value) {
        this.value = value;
    }
}
